name: tdd_with_python
dependencies:
- anaconda-client=1.4.0=py35_0
- clyent=1.2.2=py35_0
- django=1.8.4=py35_0
- openssl=1.0.2h=1
- pip=8.1.1=py35_1
- python=3.5.1=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.4=py35_0
- pyyaml=3.11=py35_4
- readline=6.2=2
- requests=2.10.0=py35_0
- setuptools=21.2.1=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - selenium==2.53.2

